
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author lucas
 */
public class MenuGrafico extends javax.swing.JFrame {

    /**
     * Creates new form MenuGrafico
     */
    OnceIdeal once;
    Nodo<Player> A;
    Nodo<Player> ZD;
    Nodo<Player> ZC;
    Nodo<Player> ZC2;
    Nodo<Player> ZI;
    Nodo<Player> MD;
    Nodo<Player> MC;
    Nodo<Player> MI;
    Nodo<Player> DD;
    Nodo<Player> DC;
    Nodo<Player> DI;

    public MenuGrafico() {
        once = new OnceIdeal();
        once.cargarTeams("Archivos/teams.csv");
        once.cargarPlayers("Archivos/players.csv");
        once.cargarMatches("Archivos/matches.csv");
        once.cargarMatchSt("Archivos/match-standings.csv");
        once.cargarEvents("Archivos/events.csv");
        initComponents();
        A = once.getMostEffectiveGoalkeeper();
        ZD = once.getMostEffectiveZD();
        ZC = once.getMostEffectiveZC(1);
        ZC2 = once.getMostEffectiveZC(2);
        ZI = once.getMostEffectiveZI();
        MD = once.getMostEffectiveMD();
        MC = once.getMostEffectiveMC();
        MI = once.getMostEffectiveMI();
        DD = once.getMostEffectiveDD();
        DC = once.getMostEffectiveDC();
        DI = once.getMostEffectiveDI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Jugador mas participativo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Arquero mas efectivo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delantero mas efectivo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Equipo mas goleador y mas goleado");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Todas las ligas de determinado jugador");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Calcular 11 ideal");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Digital-7 Mono", 1, 24)); // NOI18N
        jLabel1.setText("EL ONCE IDEAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addGap(26, 26, 26)
                .addComponent(jButton3)
                .addGap(28, 28, 28)
                .addComponent(jButton4)
                .addGap(27, 27, 27)
                .addComponent(jButton5)
                .addGap(29, 29, 29)
                .addComponent(jButton6)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Nodo<Player> jugador = once.getMostParticipativePlayer(once.listaJugadores);
        JOptionPane.showMessageDialog(this, "El jugador mas participativo es: " + jugador.getDato().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Nodo<Player> golero = once.getMostEffectiveGoalkeeper();
        JOptionPane.showMessageDialog(this, "El golero mas efectivo es: " + golero.getDato().toStringGolero());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Nodo<Player> delantero = once.getMostEffectiveForward();
        JOptionPane.showMessageDialog(this, "El delantero mas efectivo es: " + delantero.getDato().toString());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String m = JOptionPane.showInputDialog("Ingrese la temporada que desea:");
        Nodo<Team> team1 = once.getMostEffectiveTeam(Integer.parseInt(m));
        Nodo<Team> team2 = once.getLeastEffectiveTeam(Integer.parseInt(m));
        JOptionPane.showMessageDialog(this, "El equipo mas goleador es: " + team1.getDato().name + " con " + team1.getDato().getGolesHechos(Integer.parseInt(m)) + " goles" + "\n"
                + "El equipo mas goleado es: " + team2.getDato().name + " con " + team1.getDato().getGolesRecibidos(Integer.parseInt(m)) + " goles recibidos");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String j = JOptionPane.showInputDialog("Ingrese el jugador que desea las temporadas:");

        Nodo<Player> playero = once.buscarJugadorPorNombre(j);
        String ligas = playero.getDato().playerLeagues.imprimir();
        if (playero != null) {
            JOptionPane.showMessageDialog(this, "Las ligas donde jugo " + j + " son: " + "\n"
                    + ligas);
        } else {
            JOptionPane.showMessageDialog(this, "El jugador no existe", "Warning",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        JOptionPane.showMessageDialog(this,
                A.getDato().toString(Boolean.TRUE) + "\n"
                + ZD.getDato().toString(Boolean.TRUE) + "\n"
                + ZC.getDato().toString(Boolean.TRUE) + "\n"
                + ZC2.getDato().toString(Boolean.TRUE) + "\n"
                + ZI.getDato().toString(Boolean.TRUE) + "\n"
                + MD.getDato().toString(Boolean.TRUE) + "\n"
                + MC.getDato().toString(Boolean.TRUE) + "\n"
                + MI.getDato().toString(Boolean.TRUE) + "\n"
                + DD.getDato().toString(Boolean.TRUE) + "\n"
                + DC.getDato().toString(Boolean.TRUE) + "\n"
                + DI.getDato().toString(Boolean.TRUE) + "\n"
        );

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
